FROM debian:12-slim AS builder

WORKDIR /workspace

RUN apt-get update && apt-get install -y curl

RUN curl -fSL -o spc https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-linux-$(uname -m)

RUN chmod a+x spc

COPY ./static/config/craft.yml .

RUN ./spc craft

