ARG PHP_VERSION=${version:-8.2}

FROM php:${PHP_VERSION}-cli-alpine AS php_base
ENV  COMPOSER_ALLOW_SUPERUSER=1
# Install dependencies and php extensions
COPY --from=composer/composer:2.8.4-bin /composer /usr/bin/composer
COPY --from=mlocati/php-extension-installer:2.7.6 /usr/bin/install-php-extensions /usr/local/bin/

# Install php extensions
RUN install-php-extensions pdo_mysql zip amqp opcache apcu pcntl curl sockets intl xdebug
