name: Build Static PHP CLI

on:
    workflow_dispatch:

env:
  EXTENSIONS: "bcmath,curl,dom,fileinfo,gd,gettext,intl,mbstring,memcached,openssl,posix,phar,pdo,pdo_mysql,redis,tokenizer,zlib"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build-static-cli:
        strategy:
            matrix:
                variants:
                    - architecture: amd64
                      runner: ubuntu-24.04
                      version: 8.4
                    - architecture: arm64
                      runner: ubuntu-24.04-arm
                      version: 8.4

        runs-on: ${{ matrix.variants.runner }}
        name: "Build PHP ${{ matrix.variants.version }} for ${{ matrix.variants.architecture }}"
        steps:
            - name: 'Download Static PHP CLI Builder'
              uses: actions/checkout@v4
              with:
                repository: crazywhalecc/static-php-cli
                ref: 2.7.1

            - name: 'Download and prepare the PHP source'
              run: ./bin/spc-gnu-docker download --with-php=${{ matrix.variants.version }} --for-extensions=${{ env.EXTENSIONS }} --prefer-pre-built

            - name: 'Install UPX'
              run: ./bin/spc install-pkg upx

            - name: 'Build the static PHP binary'
              run: ./bin/spc-gnu-docker build ${{ env.EXTENSIONS }} --enable-zts --build-cli --with-upx-pack

            - name: 'Upload the binary as an artifact'
              uses: actions/upload-artifact@v4
              with:
                name: php-static-cli-${{ matrix.variants.version }}-${{ matrix.variants.architecture }}
                path: |
                  buildroot/bin/php




