name: Create Release

on:
    workflow_run:
        workflows: ["Build and Push Images"]
        types:
            - completed

jobs:
    release:
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
        steps:
            - name: 'Download artifact'
              uses: actions/download-artifact@v4
              id: download-artifact
              with:
                  name: tag-name
                  run-id: ${{ github.event.workflow_run.id }}
                  path: .
              continue-on-error: true

            - if: ${{ steps.download-artifact.outcome == 'success' }}
              name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Read tag name
              if: ${{ steps.download-artifact.outcome == 'success' }}
              id: tag
              run: echo "name=$(cat tag_name.txt)" >> $GITHUB_OUTPUT

            - name: Create Release
              if: ${{ steps.download-artifact.outcome == 'success' }}
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ steps.tag.outputs.name }}
                  tag_name: ${{ steps.tag.outputs.name }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
