name: Create Release

on:
    workflow_run:
        workflows: ["Build and Push Images"]
        types:
            - completed

permissions:
  contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
        steps:
            - name: 'Download Artifact From Previous Workflow'
              uses: actions/download-artifact@v5
              id: download-artifact
              with:
                  name: tag-name
                  run-id: ${{ github.event.workflow_run.id }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
              continue-on-error: false

            - if: ${{ steps.download-artifact.outcome == 'success' }}
              name: 'Check Artifact Download Outcome'
              run: |
                echo "Artifact download outcome: ${{ steps.download-artifact.outcome }}"
                ls -R

            - if: ${{ steps.download-artifact.outcome == 'success' }}
              name: 'Checkout Source Code'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - if: ${{ steps.download-artifact.outcome == 'success' }}
              name: 'Read TAG name'
              id: tag
              run: echo "name=$(cat tag_name.txt)" >> $GITHUB_OUTPUT

            - if: ${{ steps.download-artifact.outcome == 'success' }}
              name: 'Create Release'
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ steps.tag.outputs.name }}
                  tag_name: ${{ steps.tag.outputs.name }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
