name: Create Release & Packages

on:
    workflow_run:
        workflows:
            - "Build Images"
        branches:
            - main
        types:
            - completed
    push:
        branches:
            - main
        tags:
            - 'v*'
jobs:
    create-release-on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Prepare
              run: |
                echo 'The triggering workflow passed'

    abort-release-on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: Prepare
              run: |
                echo 'The triggering workflow passed'