name: Create Release & Packages

on:
    push:
#        tags:
#            - v*

permissions:
    contents: write
    packages: write
    id-token: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        env:
            DOCKER_CLI_EXPERIMENTAL: "enabled"
        strategy:
            matrix:
                php-versions:
                    - 8.4
                platforms:
                    - linux/amd64
                    - linux/arm64
                images:
                    - dockerfile: ./php/Dockerfile.roadrunner.mysql
                      image: ghcr.io/equationlabs/base-docker-images/php.roadrunner.mysql

        steps:
            - name: Checkout Source Code
              id: checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Login to Docker Hub
              id: login
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              id: qemu
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ matrix.images.image }}

#            - name: Build and push
#              uses: docker/build-push-action@v6
#              with:
#                  push: ${{ github.event_name != 'pull_request' }}
#                  platforms: ${{ matrix.platforms }}
#                  file: ${{ matrix.images.dockerfile }}
#                  tags: ${{ steps.extract-metadata.outputs.tags }}
#                  labels: ${{ steps.extract-metadata.outputs.labels }}
