FROM alpine:3.22
# Install dependencies
RUN apk add --no-cache ca-certificates curl git make bash docker && rm -rf /var/lib/apk/cache

# Set working directory
WORKDIR /usr/local/bin

# Install Skaffold
RUN curl -Lo skaffold "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-$(uname -m)"
## Install Kustomize
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
# Install Kubectl
RUN curl -Lo kubectl "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/$(uname -m)/kubectl"

# Make applications executables
RUN chmod +x skaffold kustomize kubectl

# Final image entrypoint
CMD ["bash"]
